Budget/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^upload', views.upload, name='upload'),
	url(r'^dashboard', views.dashboard, name='dashboard'),
	url(r'^Trans/(?P<datestring>\d+\-\d+)$', views.getTMonth, name='getTMonth'),
	url(r'^Trans/(?P<datestring>\d+)$', views.getTYear, name='getTYear'),
	url(r'^Trans/(?P<field>[^\/]+)/(?P<fieldvalue>[^\/]+)[\/]+$', 
        views.getTransaction, name='getTransaction'),
	url(r'^changeT$', views.changeT, name='changeT'),
	url(r'^categories', views.showCategories, name='categories'),
	url(r'^CAT', views.getCategories, name='getCat'),
	url(r'^changeCAT$', views.changeCategory, name='changeCategory'),
	url(r'^assignCategories', views.assignCategories, name='assignCategories'),
	url(r'^ChartData/(?P<budget_type>\w+)/$', 
        views.chart_data_json, name='getChartData'),
	url(r'^ChartData/(?P<budget_type>\w+)/(?P<datestring>[0-9-]+)', 
        views.chart_data_json_date, name='chart_data_json_date'),
	url(r'^showCharts', views.showCharts, name='showCharts'),
	url(r'^Accounts/$', views.getAccounts, name='accounts'),
	url(r'^changeBalance/$', views.change_balance, name='changeBalance'),
	url(r'^dailyBalance/', views.getDailyBalance, name='dailyBalance'),
	url(r'^plotDailyBalance/', views.plotDailyBalance, name='plotBalance'),
	url(r'^upload_error', views.upload_error, name='uploadError'),
]

MyBudget/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^Budget/', include('Budget.urls', namespace="budget")),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace="account")),
]

accounts/urls.py
from django.contrib.auth.views import (
    logout,
    password_change,
    password_change_done,
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete
)
from django.conf.urls import url
from .views import login_view


urlpatterns = [
    url(
        regex=r'^login/$',
        view=login_view,
        name='login',
    ),
    url(
        regex=r'^logout/$',
        view=logout,
        kwargs={'next_page': 'account:login' },
        name='logout'
    )
]

Budget/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
import json
import decimal
from django.core import exceptions
from django.utils.translation import ugettext_lazy as _
import django.utils.timezone

class Category(models.Model):
    category = models.CharField(max_length=20)
    regexp = models.CharField(max_length=400, default='')
    user = models.ForeignKey(User)

    def setReg(self, x):
        self.regexp = json.dumps(x)

    def getReg(self):
        return json.loads(self.regexp)

    def __str__(self):
        return self.category

class Account(models.Model):
    IBAN = models.CharField(max_length=34, default='XY12123412341234123412')
    name = models.CharField(max_length=50, default='Bank XY')
    description = models.CharField(max_length=200, default='Main Girokonto')
    user = models.ForeignKey(User)
    balance = models.DecimalField(max_digits=12, decimal_places=2, default = 0)

    def __str__(self):
        return self.IBAN

class Transaction(models.Model):
    user = models.ForeignKey(User)
    account = models.ForeignKey(Account)
    date = models.DateField(default=django.utils.timezone.now())
    ref = models.CharField(max_length=200, default='Reference')
    opp_name = models.CharField(max_length=80, default='Unknown')
    opp_account = models.CharField(max_length=26, default= '----')
    amount = models.DecimalField(max_digits=11, decimal_places=2, default=0)
    currency = models.CharField(max_length=20, default= 'EUR')
    category = models.CharField(max_length=50, default='Unknown')
    comment = models.CharField(max_length=100, default='')
	

accounts/models.py
from django.db import models

# Create your models here.

Budget/forms.py
from django import forms
from Budget.models import Account
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from crispy_forms.layout import *
from foundation_filefield_widget.widgets import FoundationFileInput

class AccountInputForm(forms.ModelForm):
  def __init__(self, *args, **kwargs):
    super(AccountInputForm, self).__init__(*args, **kwargs)

    self.helper = FormHelper()
    self.helper.form_class = 'form-horizontal'
    self.helper.label_class = 'col-lg-2'
    self.helper.field_class = 'col-lg-8'
    self.helper.add_input(Submit('submit', 'Save'))
    self. helper.layout = Layout(
      Field('name', placeholder='Name', required=True, autofocus=True),
      Field('IBAN', placeholder=0, required=True),
      Field('description', placeholder = "Bank XYZ", required=True),
      Field('balance', placeholder = 0, required=True)
    )

  class Meta:
    model = Account
    exclude = ('user',)

Budget/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render_to_response, render, get_object_or_404, redirect
from django.template import RequestContext
from datetime import datetime, date
from django.core.urlresolvers import reverse
from django.db.models import Sum
import collections
import json, re
from django.contrib.auth.decorators import login_required
from Budget.lib.csv_handler import csv_handler
from Budget.lib.assign_categories import assignCat
from Budget.forms import AccountInputForm
from Budget.models import Transaction, Category, Account
import calendar

import logging
logger = logging.getLogger(__name__)

@login_required
def dashboard(request):

    try:
        T = Transaction.objects.filter(user=request.user).order_by('-date')
        years = T.dates('date', 'year')
        years = years[::-1]
        Tdict = collections.OrderedDict()

        # Go through transactions and order them by year and month
        for y in years:
          # Create balance value for year
          y_int = int(y.strftime("%Y"))
          balY =  T.filter(date__year=y_int).aggregate(Sum('amount'))['amount__sum']
          tmp = collections.OrderedDict()

          Tdict[y] = { 'bal' : balY, 'months': tmp}

          month_list = T.dates('date', 'month').filter(date__year=y_int)
          month_list = month_list[::-1]
          for m in month_list:
            m_int = int(m.strftime("%m"))
            trans = T.filter(date__year=y_int).filter(date__month=m_int)
            tmpBal = trans.aggregate(Sum('amount'))['amount__sum']
            
            Tdict[y]['months'][m] = { 'bal': tmpBal }
        
        # Get accounts out of database
        acc = Account.objects.filter(user=request.user)
        Acc_dict = collections.OrderedDict()
        for a in acc:
            Acc_dict[a.name] = {'id' : a.id, 
                                'bal' : a.balance }

        context = {'trans_list': Tdict,
                   'accounts' : Acc_dict}
        return render(request, 'budget/dashboard.html', context)
    except: 
        return render(request, 'budget/dashboard.html')

def index(request):
    if request.user.is_authenticated():
        return dashboard(request)
    else:
        return redirect('account:login')


@login_required
def getDailyBalance(request):
    T = Transaction.objects.filter(user=request.user)
    T = T.values('date')\
         .annotate(dcount=Sum('amount'))\
         .order_by('-date')

    # Get accounts
    Acc = Account.objects.filter(user=request.user)

    data = []
    count = Acc.aggregate(Sum('balance'))['balance__sum']
    data.append([datetime.now().timestamp()*1000, float(count)])
    for trans in T:
        count -= trans['dcount']
        timestamp = calendar.timegm(trans['date'].timetuple())
        data.append([timestamp*1000, float(count)])

    data.reverse()
    return HttpResponse(json.dumps(data), content_type='application/json')


@login_required
def upload(request):
    if request.method == 'POST':
        # Upload files
        acc = request.POST['sel_acc']
        for _, file in request.FILES.items():
            response = csv_handler(file, request.user, acc)
            return upload_error(request, response)

    else:
        # Get accounts out of database
        acc = Account.objects.filter(user=request.user)
        Acc_dict = collections.OrderedDict()
        for a in acc:
            Acc_dict[a.name] = {'id': a.id,
                                'bal': a.balance,
                                'IBAN': a.IBAN}

        context = {'accounts': Acc_dict}
        return render(request, 'budget/upload.html', context)


@login_required
def upload_error(request, context=None):
    return render(request, 'budget/upload_error.html',
                  context)

@login_required
def getTMonth(request, datestring):
    Date = datetime.strptime(datestring, "%Y-%m")
    Trans = Transaction.objects.filter(user=request.user)
    data = Trans.filter(date__year=str(Date.year)).filter(date__month=str(Date.month)).order_by('-date')
    tmp_json = []
    for T in data:
        formDate = T.date.strftime("%Y-%m-%d")
        tmp_json.append({'Name' : T.opp_name, 'Amount' : float(T.amount), 'CUR' : T.currency, 'Reference' : T.ref, 'Date' : formDate, 'id' : T.pk, 'Category' : T.category,'Comment' : T.comment})

    return HttpResponse(json.dumps(tmp_json))

@login_required
def getTYear(request, datestring):
    Date = datetime.strptime(datestring, "%Y")
    Trans = Transaction.objects.filter(user=request.user)
    data = Trans.filter(date__year=str(Date.year)).order_by('-date')
    tmp_json = []
    for T in data:
        formDate = T.date.strftime("%Y-%m-%d")
        tmp_json.append({'Name' : T.opp_name, 'Amount' : float(T.amount), 'CUR' : T.currency, 'Reference' : T.ref, 'Date' : formDate,  'id' : T.pk , 'Category' : T.category,'Comment' : T.comment})

    return HttpResponse(json.dumps(tmp_json))

@login_required
def getTransaction(request, field, fieldvalue):
    Trans = Transaction.objects.filter(user=request.user)

    if field == 'year':
        Date = datetime.strptime(fieldvalue, "%Y")
        data = Trans.filter(date__year=str(Date.year))
    elif field == 'month':
        Date = datetime.strptime(fieldvalue, "%Y-%m")
        data = Trans.filter(date__year=str(Date.year)).filter(date__month=str(Date.month))
    elif field == 'range':
        ranges = fieldvalue.split("-")
        startDate = datetime.utcfromtimestamp(float(ranges[0]))
        endDate = datetime.utcfromtimestamp(float(ranges[1]))
        data = Trans.filter(date__range=[startDate, endDate])
    else:
        kwargs = { field : fieldvalue }
        data = Trans.filter(**kwargs)

    data = data.order_by('-date')
    tmp_json = []
    for T in data:
        tmp_json.append({'Name' : T.opp_name,#
                        'Amount' : float(T.amount),#
                        'CUR' : T.currency, #
                        'Reference' : T.ref, #
                        'Date' : T.date.strftime("%Y-%m-%d"),#
                        'id' : T.pk , #
                        'Category' : T.category,#
                        'Comment' : T.comment})

    return HttpResponse(json.dumps(tmp_json))

@login_required
def getTransaction2(request, field, fieldvalue,datevalue):
    Trans = Transaction.objects.filter(user=request.user)
    if len(datevalue) ==  4:
        Date = datetime.strptime(datevalue, "%Y")
        data = Trans.filter(date__year=str(Date.year))
    else:
        Date = datetime.strptime(datevalue, "%Y-%m")
        data = Trans.filter(date__year=str(Date.year)).filter(date__month=str(Date.month))

    kwargs = { field : fieldvalue }
    data = data.filter(**kwargs)

    data = data.order_by('-date')
    tmp_json = []
    for T in data:
        tmp_json.append({'Name' : T.opp_name,#
                        'Amount' : float(T.amount),#
                        'CUR' : T.currency, #
                        'Reference' : T.ref, #
                        'Date' : T.date.strftime("%Y-%m-%d"),#
                        'id' : T.pk , #
                        'Category' : T.category,#
                        'Comment' : T.comment})

    return HttpResponse(json.dumps(tmp_json))



@login_required
def changeT(request):
    R = request.POST
    # Check if new post
    regexp = re.compile(r'jqg\d+')
    # Change or delete existing entry
    if regexp.search(R['id']) is None:
        T = get_object_or_404(Transaction, pk=R['id'])
        if R['oper'] == 'del':
            T.delete()
            return HttpResponseRedirect(reverse('budget:index'))
    # Add new one
    else:
        T = Transaction.objects.create()

    T.date = datetime.strptime(R['Date'], '%Y-%m-%d')
    T.currency = R['CUR']
    T.opp_name = R['Name']
    T.ref = R['Reference']
    T.amount = R['Amount']
    T.category = R['Category']
    T.comment = R['Comment']
    T.save()
    return HttpResponseRedirect(reverse('budget:dashboard'))


@login_required
def getCategories(request):
    cats = Category.objects.filter(user=request.user).order_by('category')    
    
    CatDict = []
    for cat in cats:
        regs = cat.getReg()
        CatDict.append({'category': cat.category, 'regexp': regs, 'id': cat.pk })
    
    return HttpResponse(json.dumps(CatDict))

@login_required
def showCategories(request): 
    return render(request, 'budget/categories.html')

@login_required
def changeCategory(request):
    R = request.POST
    # Check if entry already exists
    regexp = re.compile(r'jqg\d+') # This is the format jqgrid returns values if
                                   # none is inserted
    if regexp.search(R['id']) is None:
        Cat = get_object_or_404(Category, pk=R['id'])
        # Check if the change is a delete
        if R['oper'] == 'del':
            Cat.delete()
            return redirect('budget:categories')

    else:
        Cat = Category.objects.create(user=request.user)

    
    Cat.category = R['category']
    Cat.setReg(R['regexp'].split(','))
    Cat.save()
    return redirect('budget:categories')

@login_required
def assignCategories(request):
    assignCat(request.user)
    return redirect('budget:dashboard')

@login_required
def chart_data_json_date(request, budget_type, datestring):
    data = []
    # Query transactions for user
    T = Transaction.objects.filter(user=request.user)

    # Check if datestring is year or year-month
    if len(datestring)==4:
        T = T.filter(date__year=datestring)
    elif len(datestring)==7:
        Date = datetime.strptime(datestring, "%Y-%m")
        T = T.filter(date__year=str(Date.year), date__month=str(Date.month))
    elif len(datestring) >= 15:
        ranges = datestring.split('-')
        startDate = datetime.utcfromtimestamp(float(ranges[0]))
        endDate = datetime.utcfromtimestamp(float(ranges[1]))
        T = T.filter(date__range=[startDate, endDate])
    # Check for Einnahmen
    if budget_type == 'Einnahmen':

accounts/views.py
from django.shortcuts import render_to_response, HttpResponseRedirect
from django.views.generic import FormView
from django.template import RequestContext
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse

def login_view(request):
    # Force logout.
    logout(request)
    username = password = ''

    # Flag to keep track whether the login was invalid.
    login_failed = False

    if request.POST:
        username = request.POST['username'].replace(' ', '')
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('budget:dashboard'))
        else:
            login_failed = True

    return render_to_response('accounts/login.html',
                              {'login_failed': login_failed})

Budget/templates/budget/accounts_create.html
{% extends 'accounts.html' %}

{% load crispy_forms_tags %}

{% block main %}
    <h1><span class="fa fa-plus"></span> Konto hinzufügen </h1>
   {% crispy form %}
{% endblock %}

{% block customjs %}
<script type="text/javascript">
$(function () {
    // Sets the value of the submit_button_type field if the 'Submit & Add
    // Another button is clicked.
    $('#submit-id-submit_and_add').click(function() {
        $('#id_submit_button_type').val('submit_and_add');
    });
});

</script>
{% endblock %}

Budget/templates/budget/categories.html
{% extends 'base.html' %}

{% block main %}
<div class="container">
    <h1 class="page-header"> Categories </h1>
        <div class="jQueryUI" >
            <table id="jqGrid_Cat"></table>
            <div id="jqGridPager_Cat"></div>
        </div>
    <a href="{% url 'budget:assignCategories' %}"> Go through transaction and assign categories  </a>   
</div>
{% endblock %} 



{% block custom_js %}
<script type="text/ecmascript">
var lastsel;
var current;

var grid= '#jqGrid_Cat'; // ID of the grid
var pager = '#jqGridPager_Cat'; // ID of the grid pager

var editOptions = {
        keys: true,
        aftersavefunc: function() {
            $(grid).jqGrid('setGridParam',{datatype:'json'}).trigger("reloadGrid");
        },
    };

$(document).ready(function() {
    // Get transactions
    // Delete old table

    // Load data
    $(grid).jqGrid(
      {
      url: "{% url 'budget:getCat' %}",
      mtype: "GET",
      datatype: "json",
      colModel: [
        { label: 'Category', name: 'category', width: 150, editable:true, sorttype:'text' },
        { label: 'Regular Expressions', name: 'regexp', width: 100, editable:true},
        { index: 'id', label: 'id', name: 'id', width: 10},
      ],
     viewrecords: true,
     autowidth: true,
     autoheight: true,
     loadonce: true,
     rowNum: 1000,
     pager: pager,
     sortname: 'Date',
     sortorder: "desc",
     onSelectRow: function(id) { 
        if(id && id!==lastsel){ jQuery(grid).jqGrid('restoreRow',lastsel); jQuery(grid).jqGrid('editRow', id, true); lastsel=id; } }, 
     editurl: "{% url 'budget:changeCategory' %}",
      //editData: { csrfmiddlewaretoken: '{{ csrf_token }}'},
    });
    $(grid).jqGrid('navGrid',pager,{edit:false,add:false,del:true});
    $(grid).jqGrid('inlineNav',pager,{
        addParams : {
            addRowParams: editOptions
        },
        editParams: editOptions
    });
});
</script>
{% endblock %}

Budget/templates/budget/charts.html
{% extends "Budget/dashboard.html" %}

{% block title %} my personal budget {% endblock %}

{% block main %}
      <div class="panel panel-default">
        <div id="chart_panel" class="panel-body" 
            style="width:50%"></div>
    </div>
{% endblock %}

{% block custom_js %}
<script src="{{ STATIC_URL }}highcharts/js/highcharts.js"></script>
<script type="text/javascript">
$(document).ready(function() {

    // Glucose Average by Day chart
     var Pi = {
        chart: {
            renderTo: 'chart_panel',
        },
        title: {text: 'Ausgaben'},
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    }
                }
            }
        },
        series: [{
            type: 'pie',
            name: 'Ausgaben',
        }]
    };

    var chartDataUrl = "{% url 'budget:getChartData' %}";
    $.getJSON(chartDataUrl,
        function(data) {
            Pi.series[0].data = data;
            var chart = new Highcharts.Chart(Pi);
    });

} );
</script>

{% endblock %}

Budget/templates/budget/daily_plot.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block main %}
<div id="dailyPlot" style="min-width: 310px; height: 400px; margin: 0 auto"></div>


{% endblock %}
{% block custom_js %}
<script src="{% static 'highcharts/js/highcharts.js' %}"></script>
<script src="{% static 'js/charts.js' %}"></script>
<script type="text/ecmascript">

$(function () {
    var chartDataUrl = "{% url 'budget:dailyBalance' %}";
    dailyPlot('#dailyPlot', chartDataUrl);
});
</script>
{% endblock %}

Budget/templates/budget/dashboard.html
<!-- Load extensions -->
{% extends 'base.html' %}
{% load staticfiles %}
{% block main %}

<!-- Begin Page Content -->
<div class="container">
  <h1 class="page-header"> Dashboard </h1>
  <!-- Daily Balance Plot -->
  <div class="clod-md-10">
    <div id="dailyPlot"
         style="min-width: 310px; height: 200px; margin: 0 auto">
  </div>
  <!-- Categories Plot -->
  <div class="row placeholders">
    <div class="col-md-5">
      <div id="chart_panel_l" 
           style="height: 300px;display: inline-block; margin: 0 auto"></div>
    </div>
    <div class="col-md-5">
      <div id="chart_panel_r" 
           style="height: 300px;display: inline-block"></div>
    </div>
  </div>
</div>
<div class="container">
  {% if accounts %}
    {% for acc_name, acc in accounts.items %}
      <h2 class="page-header"> Account: {{acc_name }} | Balance: 
        <span id="{{ acc.id }}" class="balance" contenteditable="true">
          {{ acc.bal }}
        </span> €
      </h2>
   {% endfor %}
  {% endif %}
  <div id="CategoryTransactionDIV"></div>
  {% if trans_list %}
    {% for year, val1 in trans_list.items %}
      <div data-toggle="collapse" data-target="#DIV{{year|date:'Y'}}" 
           class="yearDiv"> 
        <span class="col-md-2"> {{ year|date:"Y" }} </span>
          <button type="button" class="btn btn-primary btn-xs 
          dateTrans no-collapsable" data-date="{{ year|date:'Y'}}"> 
            Plot 
          </button>
          <button class="btn btn-primary btn-xs no-collapsable trans" 
                  href="{% url 'budget:getTYear' year|date:'Y' %}" 
                  data-date="{{ year|date:'Y'}}"> Transactions </button>
        <span style="float:right"> {{ val1.bal }} &euro; </span> 
      </div>
      <div id="{{ year|date:'Y'}}DIV"> </div>
      <div id="DIV{{ year|date:"Y" }}" class="collapse" >
      {% for month, values in val1.months.items %}
        <div class="col-md-12 month">
          <span class="col-md-2" style="float:left"> {{ month|date:"F" }} 
          </span>
          <button type="button" class="btn btn-primary btn-xs dateTrans" 
                  data-date="{{ month|date:'Y-m'}}"> Plot </button> 
          <span> {{ values.bal }} &euro; </span>
          <button type="button" class="btn btn-primary btn-xs trans" 
                  data-date="{{ month|date:'Y-m'}}" 
                  href="{% url 'budget:getTMonth' month|date:'Y-m' %}"> 
            Transactions 
          </button>
        </div>
        <div id="{{ month|date:'Y-m'}}DIV"> </div>
      {% endfor %}
      </div>
    {% endfor %}
  {% else %}
      <p> No balances are available. </p>
  {% endif %}
  <table id="jqGrid"></table>
  <div id="jqGridPager"></div>
</div>

{% block modals %}
{% endblock %}

{% endblock %} 

{% block custom_js %}
<script src="{% static 'highcharts/js/highcharts.js' %}"></script>
<script src="{% static 'js/charts.js' %}"></script>
<script type="text/ecmascript">

var lastsel;
var current; // remove in final version
var openTable;
var grid = '#jqGrid'; 
var pager = '#jqGridPager';
var datestringR = '';
var editUrl = "{% url 'budget:changeT' %}";
var indexUrl = "{% url 'budget:index' %}";

$(document).ready(function() {
  // Get transactions
  $(".trans").click(function (e) {
    // Prevent the page to follow link
    e.preventDefault();
    // Delete old table
    $(grid).jqGrid("GridUnload");
    $(pager).remove();
    $(grid).remove();
    // Looks if table is already present and creates DIV + datatable if not 
    if(current !== $(this).attr('data-date')) {
      // Initialize div
      current = $(this).attr('data-date');
      $("#"+$(this).attr('data-date')+"DIV").append("<div class='jQueryUI'><table id="+grid.substring(1)+"></table><div id="+pager.substring(1)+"></div></div>");
      buildTable(grid, $(this).attr('href'), editUrl);
      }
    // Deletes table if already present (double click on that entry)
    else { 
      current = ''; 
      $("#"+$(this).attr('data-date')+"DIV").append("<div class='jQueryUI'><table id="+grid.substring(1)+"></table><div id="+pager.substring(1)+"></div></div>");
    }
    });

  
 // Ausgaben Chart
    var chartDataUrl = "{% url 'budget:getChartData' 'Ausgaben' %}";
    var tableDataUrl = "{% url 'budget:index' %}" + "Trans/category/";
    var pi_chartR = pi_chart('chart_panel_r', chartDataUrl, 'Ausgaben', 
                          '#CategoryTransactionDIV', grid, tableDataUrl);

    // Einnahmen Chart                      
    var chartDataUrl = "{% url 'budget:getChartData' 'Einnahmen' %}";
    var pi_chartL = pi_chart('chart_panel_l', chartDataUrl, 'Einnahmen', 
                          '#CategoryTransactionDIV', grid, tableDataUrl);
    // Time Chart 
    var budget_over_time = time_chart('dailyPlot',
                                      "{% url 'budget:dailyBalance' %}",
                                      'Budget over time',
                                      '#CategoryTransactionDIV', grid, 
                                      "{% url 'budget:index' %}" + "Trans/", 
                                      pi_chartL, pi_chartR);
                               
    $(".dateTrans").click(function (e) {
    datestringR = $(this).attr('data-date');
    var chartDataUrl = "{% url 'budget:getChartData' 'Ausgaben'%}"+datestringR;
    $.getJSON(chartDataUrl,
        function(data) {
            pi_chartR.title.text = "Ausgaben " + datestringR;
            pi_chartR.series[0].setData(data,true);
    });

    var chartDataUrl = "{% url 'budget:getChartData' 'Einnahmen'%}"+$(this).attr('data-date');
    $.getJSON(chartDataUrl,
        function(data) {
            pi_chartL.series[0].setData(data, true);
            //var chartL = new Highcharts.Chart(pi_chartL);
    });
    });
});


// Fix Bug
$('.no-collapsable').on('click', function (e) {
    e.stopPropagation();
});

// Check if balance has changed
var acc_bal = $('.balance').text();
$( '.balance' ).blur(function(e) {
  if ($(this).text() != acc_bal) {
    var acc_id = $(this).attr('id');
    var acc_bal = $(this).text();
    $.get("{% url 'budget:changeBalance' %}", 
          {account_id: acc_id,
           account_bal: acc_bal
          },
         function(response_data){
         $("#"+acc_id).text(response_data);
         });
  }
});
</script>
{% block custom_js2 %} {% endblock %}
{% endblock %}

Budget/templates/budget/index.html
{% extends "base.html" %}

{% block customcss %}
    <style>
        body {margin-top: 40px;
        padding-top: 40px;
  			padding-bottom: 20px;}
    </style>
{% endblock %}

{% block title %} my personal budget {% endblock %}

{% block main %}
    <h2> Please Log in! </h2>
{% endblock %}

Budget/templates/budget/upload.html
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">X</button>
    <h1>Upload CSV</h1>
</div>
<form action="{% url 'budget:upload' %}" method="post" 
      enctype="multipart/form-data">
  <div class="modal-body">
    {% csrf_token %}
    <label class="control-label">Select File</label>
    <div class="input-group">
      <span class="input-group-btn">
        <span class="btn btn-primary" 
              onclick="$(this).parent().find('input[type=file]').click();">
              Browse
        </span>
        <input name="uploaded_file" 
               onchange="$(this).parent().parent().find('.form-control').
               html($(this).val().split(/[\\|/]/).pop());" style="display: none;" 
               type="file">
      </span>
      <span class="form-control"></span>
    </div>
    <div class="form-group">
      <label for id='sel_acc' class="control-label">Select Account</label>
      <select class="form-control" name="sel_acc">
        {% for acc_name, acc in accounts.items %}
        <option value={{acc.id}}> {{acc_name}} ({{acc.IBAN}})</option>
        {% endfor %}
      </select>
    </div>
  </div>
  <div class="modal-footer">
    <input type="submit" class="btn btn-primary" value="Upload">
    <button type="button" class="btn btn-default" data-dismiss="modal">
      Close
    </button>
  </div>
</form>