Budget/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^upload', views.upload, name='upload'),
	url(r'^dashboard', views.dashboard, name='dashboard'),
	url(r'^Trans/(?P<datestring>\d+\-\d+)$', views.getTMonth, name='getTMonth'),
	url(r'^Trans/(?P<datestring>\d+)$', views.getTYear, name='getTYear'),
	url(r'^Trans/(?P<field>[^\/]+)/(?P<fieldvalue>[^\/]+)[\/]+$', 
        views.getTransaction, name='getTransaction'),
	url(r'^changeT$', views.changeT, name='changeT'),
	url(r'^categories', views.showCategories, name='categories'),
	url(r'^CAT', views.getCategories, name='getCat'),
	url(r'^changeCAT$', views.changeCategory, name='changeCategory'),
	url(r'^assignCategories', views.assignCategories, name='assignCategories'),
	url(r'^ChartData/(?P<budget_type>\w+)/$', 
        views.chart_data_json, name='getChartData'),
	url(r'^ChartData/(?P<budget_type>\w+)/(?P<datestring>[0-9-]+)', 
        views.chart_data_json_date, name='chart_data_json_date'),
	url(r'^showCharts', views.showCharts, name='showCharts'),
	url(r'^Accounts/$', views.getAccounts, name='accounts'),
	url(r'^changeBalance/$', views.change_balance, name='changeBalance'),
	url(r'^dailyBalance/', views.getDailyBalance, name='dailyBalance'),
	url(r'^plotDailyBalance/', views.plotDailyBalance, name='plotBalance'),
	url(r'^upload_error', views.upload_error, name='uploadError'),
]

MyBudget/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^Budget/', include('Budget.urls', namespace="budget")),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace="account")),
]

accounts/urls.py
from django.contrib.auth.views import (
    logout,
    password_change,
    password_change_done,
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete
)
from django.conf.urls import url
from .views import login_view


urlpatterns = [
    url(
        regex=r'^login/$',
        view=login_view,
        name='login',
    ),
    url(
        regex=r'^logout/$',
        view=logout,
        kwargs={'next_page': 'account:login' },
        name='logout'
    )
]

Budget/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
import json
import decimal
from django.core import exceptions
from django.utils.translation import ugettext_lazy as _
import django.utils.timezone

class Category(models.Model):
    category = models.CharField(max_length=20)
    regexp = models.CharField(max_length=400, default='')
    user = models.ForeignKey(User)

    def setReg(self, x):
        self.regexp = json.dumps(x)

    def getReg(self):
        return json.loads(self.regexp)

    def __str__(self):
        return self.category

class Account(models.Model):
    IBAN = models.CharField(max_length=34, default='XY12123412341234123412')
    name = models.CharField(max_length=50, default='Bank XY')
    description = models.CharField(max_length=200, default='Main Girokonto')
    user = models.ForeignKey(User)
    balance = models.DecimalField(max_digits=12, decimal_places=2, default = 0)

    def __str__(self):
        return self.IBAN

class Transaction(models.Model):
    user = models.ForeignKey(User)
    account = models.ForeignKey(Account)
    date = models.DateField(default=django.utils.timezone.now())
    ref = models.CharField(max_length=200, default='Reference')
    opp_name = models.CharField(max_length=80, default='Unknown')
    opp_account = models.CharField(max_length=26, default= '----')
    amount = models.DecimalField(max_digits=11, decimal_places=2, default=0)
    currency = models.CharField(max_length=20, default= 'EUR')
    category = models.CharField(max_length=50, default='Unknown')
    comment = models.CharField(max_length=100, default='')
	

Budget/forms.py
from django import forms
from Budget.models import Account
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from crispy_forms.layout import *
from foundation_filefield_widget.widgets import FoundationFileInput

class AccountInputForm(forms.ModelForm):
  def __init__(self, *args, **kwargs):
    super(AccountInputForm, self).__init__(*args, **kwargs)

    self.helper = FormHelper()
    self.helper.form_class = 'form-horizontal'
    self.helper.label_class = 'col-lg-2'
    self.helper.field_class = 'col-lg-8'
    self.helper.add_input(Submit('submit', 'Save'))
    self. helper.layout = Layout(
      Field('name', placeholder='Name', required=True, autofocus=True),
      Field('IBAN', placeholder=0, required=True),
      Field('description', placeholder = "Bank XYZ", required=True),
      Field('balance', placeholder = 0, required=True)
    )

  class Meta:
    model = Account
    exclude = ('user',)

Budget/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render_to_response, render, get_object_or_404, redirect
from django.template import RequestContext
from datetime import datetime, date
from django.core.urlresolvers import reverse
from django.db.models import Sum
import collections
import json, re
from django.contrib.auth.decorators import login_required
from Budget.lib.csv_handler import csv_handler
from Budget.lib.assign_categories import assignCat
from Budget.forms import AccountInputForm
from Budget.models import Transaction, Category, Account
import calendar

import logging
logger = logging.getLogger(__name__)

@login_required
def dashboard(request):

    try:
        T = Transaction.objects.filter(user=request.user).order_by('-date')
        years = T.dates('date', 'year')
        years = years[::-1]
        Tdict = collections.OrderedDict()

        # Go through transactions and order them by year and month
        for y in years:
          # Create balance value for year
          y_int = int(y.strftime("%Y"))
          balY =  T.filter(date__year=y_int).aggregate(Sum('amount'))['amount__sum']
          tmp = collections.OrderedDict()

          Tdict[y] = { 'bal' : balY, 'months': tmp}

          month_list = T.dates('date', 'month').filter(date__year=y_int)
          month_list = month_list[::-1]
          for m in month_list:
            m_int = int(m.strftime("%m"))
            trans = T.filter(date__year=y_int).filter(date__month=m_int)
            tmpBal = trans.aggregate(Sum('amount'))['amount__sum']
            
            Tdict[y]['months'][m] = { 'bal': tmpBal }
        
        # Get accounts out of database
        acc = Account.objects.filter(user=request.user)
        Acc_dict = collections.OrderedDict()
        for a in acc:
            Acc_dict[a.name] = {'id' : a.id, 
                                'bal' : a.balance }

        context = {'trans_list': Tdict,
                   'accounts' : Acc_dict}
        return render(request, 'budget/dashboard.html', context)
    except: 
        return render(request, 'budget/dashboard.html')

def index(request):
    if request.user.is_authenticated():
        return dashboard(request)
    else:
        return redirect('account:login')


@login_required
def getDailyBalance(request):
    T = Transaction.objects.filter(user=request.user)
    T = T.values('date')\
         .annotate(dcount=Sum('amount'))\
         .order_by('-date')

    # Get accounts
    Acc = Account.objects.filter(user=request.user)

    data = []
    count = Acc.aggregate(Sum('balance'))['balance__sum']
    data.append([datetime.now().timestamp()*1000, float(count)])
    for trans in T:
        count -= trans['dcount']
        timestamp = calendar.timegm(trans['date'].timetuple())
        data.append([timestamp*1000, float(count)])

    data.reverse()
    return HttpResponse(json.dumps(data), content_type='application/json')


@login_required
def upload(request):
    if request.method == 'POST':
        # Upload files
        acc = request.POST['sel_acc']
        for _, file in request.FILES.items():
            response = csv_handler(file, request.user, acc)
            return upload_error(request, response)

    else:
        # Get accounts out of database
        acc = Account.objects.filter(user=request.user)
        Acc_dict = collections.OrderedDict()
        for a in acc:
            Acc_dict[a.name] = {'id': a.id,
                                'bal': a.balance,
                                'IBAN': a.IBAN}

        context = {'accounts': Acc_dict}
        return render(request, 'budget/upload.html', context)


@login_required
def upload_error(request, context=None):
    return render(request, 'budget/upload_error.html',
                  context)

@login_required
def getTMonth(request, datestring):
    Date = datetime.strptime(datestring, "%Y-%m")
    Trans = Transaction.objects.filter(user=request.user)
    data = Trans.filter(date__year=str(Date.year)).filter(date__month=str(Date.month)).order_by('-date')
    tmp_json = []
    for T in data:
        formDate = T.date.strftime("%Y-%m-%d")
        tmp_json.append({'Name' : T.opp_name, 'Amount' : float(T.amount), 'CUR' : T.currency, 'Reference' : T.ref, 'Date' : formDate, 'id' : T.pk, 'Category' : T.category,'Comment' : T.comment})

    return HttpResponse(json.dumps(tmp_json))

@login_required
def getTYear(request, datestring):
    Date = datetime.strptime(datestring, "%Y")
    Trans = Transaction.objects.filter(user=request.user)
    data = Trans.filter(date__year=str(Date.year)).order_by('-date')
    tmp_json = []
    for T in data:
        formDate = T.date.strftime("%Y-%m-%d")
        tmp_json.append({'Name' : T.opp_name, 'Amount' : float(T.amount), 'CUR' : T.currency, 'Reference' : T.ref, 'Date' : formDate,  'id' : T.pk , 'Category' : T.category,'Comment' : T.comment})

    return HttpResponse(json.dumps(tmp_json))

@login_required
def getTransaction(request, field, fieldvalue):
    Trans = Transaction.objects.filter(user=request.user)

    if field == 'year':
        Date = datetime.strptime(fieldvalue, "%Y")
        data = Trans.filter(date__year=str(Date.year))
    elif field == 'month':
        Date = datetime.strptime(fieldvalue, "%Y-%m")
        data = Trans.filter(date__year=str(Date.year)).filter(date__month=str(Date.month))
    elif field == 'range':
        ranges = fieldvalue.split("-")
        startDate = datetime.utcfromtimestamp(float(ranges[0]))
        endDate = datetime.utcfromtimestamp(float(ranges[1]))
        data = Trans.filter(date__range=[startDate, endDate])
    else:
        kwargs = { field : fieldvalue }
        data = Trans.filter(**kwargs)

    data = data.order_by('-date')
    tmp_json = []
    for T in data:
        tmp_json.append({'Name' : T.opp_name,#
                        'Amount' : float(T.amount),#
                        'CUR' : T.currency, #
                        'Reference' : T.ref, #
                        'Date' : T.date.strftime("%Y-%m-%d"),#
                        'id' : T.pk , #
                        'Category' : T.category,#
                        'Comment' : T.comment})

    return HttpResponse(json.dumps(tmp_json))

@login_required
def getTransaction2(request, field, fieldvalue,datevalue):
    Trans = Transaction.objects.filter(user=request.user)
    if len(datevalue) ==  4:
        Date = datetime.strptime(datevalue, "%Y")
        data = Trans.filter(date__year=str(Date.year))
    else:
        Date = datetime.strptime(datevalue, "%Y-%m")
        data = Trans.filter(date__year=str(Date.year)).filter(date__month=str(Date.month))

    kwargs = { field : fieldvalue }
    data = data.filter(**kwargs)

    data = data.order_by('-date')
    tmp_json = []
    for T in data:
        tmp_json.append({'Name' : T.opp_name,#
                        'Amount' : float(T.amount),#
                        'CUR' : T.currency, #
                        'Reference' : T.ref, #
                        'Date' : T.date.strftime("%Y-%m-%d"),#
                        'id' : T.pk , #
                        'Category' : T.category,#
                        'Comment' : T.comment})

    return HttpResponse(json.dumps(tmp_json))



@login_required
def changeT(request):
    R = request.POST
    # Check if new post
    regexp = re.compile(r'jqg\d+')
    # Change or delete existing entry
    if regexp.search(R['id']) is None:
        T = get_object_or_404(Transaction, pk=R['id'])
        if R['oper'] == 'del':
            T.delete()
            return HttpResponseRedirect(reverse('budget:index'))
    # Add new one
    else:
        T = Transaction.objects.create()

    T.date = datetime.strptime(R['Date'], '%Y-%m-%d')
    T.currency = R['CUR']
    T.opp_name = R['Name']
    T.ref = R['Reference']
    T.amount = R['Amount']
    T.category = R['Category']
    T.comment = R['Comment']
    T.save()
    return HttpResponseRedirect(reverse('budget:dashboard'))


@login_required
def getCategories(request):
    cats = Category.objects.filter(user=request.user).order_by('category')    
    
    CatDict = []
    for cat in cats:
        regs = cat.getReg()
        CatDict.append({'category': cat.category, 'regexp': regs, 'id': cat.pk })
    
    return HttpResponse(json.dumps(CatDict))

@login_required
def showCategories(request): 
    return render(request, 'budget/categories.html')

@login_required
def changeCategory(request):
    R = request.POST
    # Check if entry already exists
    regexp = re.compile(r'jqg\d+') # This is the format jqgrid returns values if
                                   # none is inserted
    if regexp.search(R['id']) is None:
        Cat = get_object_or_404(Category, pk=R['id'])
        # Check if the change is a delete
        if R['oper'] == 'del':
            Cat.delete()
            return redirect('budget:categories')

    else:
        Cat = Category.objects.create(user=request.user)

    
    Cat.category = R['category']
    Cat.setReg(R['regexp'].split(','))
    Cat.save()
    return redirect('budget:categories')

@login_required
def assignCategories(request):
    assignCat(request.user)
    return redirect('budget:dashboard')

@login_required
def chart_data_json_date(request, budget_type, datestring):
    data = []
    # Query transactions for user
    T = Transaction.objects.filter(user=request.user)

    # Check if datestring is year or year-month
    if len(datestring)==4:
        T = T.filter(date__year=datestring)
    elif len(datestring)==7:
        Date = datetime.strptime(datestring, "%Y-%m")
        T = T.filter(date__year=str(Date.year), date__month=str(Date.month))
    elif len(datestring) >= 15:
        ranges = datestring.split('-')
        startDate = datetime.utcfromtimestamp(float(ranges[0]))
        endDate = datetime.utcfromtimestamp(float(ranges[1]))
        T = T.filter(date__range=[startDate, endDate])
    # Check for Einnahmen
    if budget_type == 'Einnahmen':

Budget/templates/base.html
{% load staticfiles %}
{% load compress %}

<!DOCTYPE html>
<html lang="en">

<head> 
  <!-- Site header -->
  <title>{% block title %} my personal budget {% endblock %}</title>
  <meta charset="utf-8" />
  <!-- CSS -->
  <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet"> 
  <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <link rel="stylesheet" type="text/css" media="screen" href="{% static 'jquery/css/jquery-ui.theme.css' %}" >
  <link rel="stylesheet" type="text/css" media="screen" href="{% static 'jqGrid/css/ui.jqgrid.css' %}"> 
  <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/main.css' %}">

  {% block customcss %}
  <style>
    body {padding-bottom: 40px;}
  </style>
  {% endblock %}
  {% block extracss %} {% endblock %}
</head>

<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse"
          data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'budget:dashboard' %}">
          <span class="fa fa-book"></span>  my personal budget </a>
        {% else %}
        <a class="navbar-brand" href="{% url 'budget:index' %}">
          <span class="fa fa-bank"></span>  my personal budget </a>
        {% endif %}
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li>
            <a href="{% url 'budget:upload' %}" 
               data-target="#uploadModal" data-toggle="modal">
            <span class="fa fa-plus"></span>&nbsp;Upload CSV</a>
          </li>

          <li><a href="{% url 'budget:dashboard' %}">
            <span class="fa fa-th"></span>&nbsp;Dashboard</a>
          </li>
          <li><a href="{% url 'budget:categories' %}">
            Categories </a>
          </li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <span class="fa fa-user"></span>&nbsp;
            {{ user }} <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'budget:accounts' %}">Accounts</a>
            <li><a href="{% url 'account:logout' %}">Log Out</a></li>
          </li>
          </ul>
          </li>
          {% else %}
          <form class="navbar-form navbar-right">
          <button type="button" class="btn btn-primary"
            onclick="location.href=&quot;{% url 'account:login' %}&quot;;">
            Log In</button>
          </form>
          {% endif %}
        </ul>
      </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav>
 
  <div id="uploadModal" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content"></div>
    </div>
  </div>
  {% block main %} 
  {% endblock %}
</body>

{% compress js %}
<script type="text/ecmascript" src="{% static 'jquery/js/jquery.min.js' %}"></script> 
<script type="text/ecmascript" src="{% static 'jqGrid/js/jquery.jqGrid.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<!-- Localization -->
<script type="text/ecmascript" src="{% static 'jqGrid/js/i18n/grid.locale-en.js' %}"></script>
{% endcompress %}

{% block custom_js %} 
{% endblock %}